-- Poll app schema. Hibernate runs with ddl-auto=validate, so entities must match this exactly.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)              NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE poll (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id   VARCHAR(12)              NOT NULL,
    creator_id BIGINT                   NOT NULL,
    question   VARCHAR(300)             NOT NULL,
    status     VARCHAR(10)              NOT NULL DEFAULT 'OPEN',
    version    BIGINT                   NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_poll_share_id UNIQUE (share_id),
    CONSTRAINT fk_poll_creator FOREIGN KEY (creator_id) REFERENCES users (id)
);
CREATE INDEX idx_poll_creator_id ON poll (creator_id);

CREATE TABLE poll_option (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id     BIGINT       NOT NULL,
    option_text VARCHAR(100) NOT NULL,
    position    INT          NOT NULL,
    vote_count  INT          NOT NULL DEFAULT 0,
    CONSTRAINT ck_poll_option_vote_count CHECK (vote_count >= 0),
    CONSTRAINT fk_poll_option_poll FOREIGN KEY (poll_id) REFERENCES poll (id)
);
CREATE INDEX idx_poll_option_poll_id ON poll_option (poll_id);

-- One row per (user, poll): the user's current vote. History lives in audit_event.
-- fk_vote_option has no ON DELETE: the DB refuses to delete an option that still has votes.
CREATE TABLE vote (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id    BIGINT                   NOT NULL,
    user_id    BIGINT                   NOT NULL,
    option_id  BIGINT                   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_vote_user_poll UNIQUE (user_id, poll_id),
    CONSTRAINT fk_vote_poll FOREIGN KEY (poll_id) REFERENCES poll (id),
    CONSTRAINT fk_vote_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_vote_option FOREIGN KEY (option_id) REFERENCES poll_option (id)
);
CREATE INDEX idx_vote_poll_id ON vote (poll_id);
CREATE INDEX idx_vote_option_id ON vote (option_id);

-- Only the SHA-256 hex of the bearer token is stored.
CREATE TABLE auth_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    token_hash CHAR(64)                 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_auth_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_auth_token_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_auth_token_user_id ON auth_token (user_id);

-- Append-only log of every action. The entity maps actor_id / poll_id as plain Long columns.
CREATE TABLE audit_event (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id   BIGINT,
    action     VARCHAR(30)              NOT NULL,
    poll_id    BIGINT,
    details    VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_audit_event_actor FOREIGN KEY (actor_id) REFERENCES users (id)
);
CREATE INDEX idx_audit_event_poll_id ON audit_event (poll_id);
CREATE INDEX idx_audit_event_actor_id ON audit_event (actor_id);
